language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm i
script:
  - npm run build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
